name: main
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: setup
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.100-preview.5.23303.2'

    - name: restore
      run: dotnet restore

    - name: build
      run: dotnet build --configuration Release --no-restore

  push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: setup
        uses: docker/setup-buildx-action@v2

      - name: login
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: build and push
        uses: docker/build-push-action@v3
        with:
          tags: ghcr.io/jezielmoura/imageoptimize:${{ github.sha }}
          push: true